import {
    clearNotesForContext,
    getNoteFromDb,
    deleteNoteFromDb,
    clearScreenshotsForContext,
    getScreenshotFromDb,
    deleteScreenshotFromDb,
} from '../../utils/db.js';

export const lightThemeColors = {
    blue: '#1A73E8',
    red: '#D93025',
    yellow: '#F9AB00',
    green: '#188038',
    pink: '#D01884',
    purple: '#A142F4',
    cyan: '#007B83',
    orange: '#FA903E',
    grey: '#5F6368',
};

export const darkThemeColors = {
    blue: '#8AB4F8',
    red: '#F28B82',
    yellow: '#FDD663',
    green: '#81C995',
    pink: '#FF8BCB',
    purple: '#C58AF9',
    cyan: '#78D9EC',
    orange: '#FCAD70',
    grey: '#DADCE0',
};

export const colors = ['grey', 'blue', 'red', 'yellow', 'green', 'pink', 'purple', 'cyan', 'orange'];

export const STORAGE_KEYS = {
    ORDER: 'userGroupOrder',
    PINS: 'pinnedGroupIds',
    HIDDEN: 'hiddenGroupIds',
    SETTINGS: 'listGroupSettings',
    PINNED_AT_LAST: 'pinnedAtLastPositionId',
    API_KEY: 'geminiApiKey',
    SPLIT_SCREEN: 'splitScreenState',
    SCREENSHOTS: 'groupScreenshots',
    NOTES: 'groupNotes',
    PERSISTENT_NOTES: 'persistentNoteIds',
    GEMINI_SCHEDULES: 'geminiSchedules',
    PERSISTENT_GEMINI: 'persistentGeminiConversationIds',
    GEMINI_SESSION_CONVERSATIONS: 'geminiSessionConversations',
    PERSISTENT_SCREENSHOTS: 'persistentScreenshotIds',
    VISIBILITY: 'visibilitySettings',
    ACTION_VISIBILITY: 'actionVisibilitySettings',
    BOOKMARK_ACTION_VISIBILITY: 'bookmarkActionVisibilitySettings',
    BROKEN_BOOKMARKS_SESSION: 'brokenBookmarksCache',
    IS_LIST_GROUP_PINNED: 'isListGroupPinned',
    IS_GEMINI_PINNED: 'isGeminiPinned',
    ORPHAN_SECTION_DISPLAY: 'orphanSectionDisplayMode',
};

export const MAX_GEMINI_SCHEDULES = 7;

export const ACTION_GROUPS = {
    backup: { classes: ['backup-btn'], tooltip: 'backupGroup' },
    restore: { classes: ['restore-btn'], tooltip: 'restoreGroup' },
    pin: { classes: ['pin-btn'], tooltip: 'unpinGroup' },
    hide: { classes: ['hide-group-btn'], tooltip: 'hideGroup' },
    'create-rule': { classes: ['create-rule-btn'], tooltip: 'createRuleFromSubgroup' },
    'add-to-rule': { classes: ['add-to-rule-btn'], tooltip: 'addSubgroupToExistingRule' },
    copy: { classes: ['copy-group-urls-btn', 'copy-subgroup-urls-btn', 'copy-tab-url-btn'], tooltip: 'copyUrl' },
    'delete-group': { classes: ['delete-group-btn', 'delete-subgroup-btn'], tooltip: 'deleteGroupTabs' },
    'delete-tab': { classes: ['delete-tab-btn'], tooltip: 'closeTab' },
    notes: { classes: ['view-notes-btn'], tooltip: 'viewNotes' },
    themes: { classes: ['page-mode-btn'], tooltip: 'openThemeSelector' },
    split: { classes: ['split-screen-btn'], tooltip: 'splitScreen' },
    panel: { classes: ['open-in-panel-btn'], tooltip: 'openInPanel' },
    pip: { classes: ['pip-btn'], tooltip: 'openAsPipTitle' },
    'video-pip': { classes: ['video-pip-btn'], tooltip: 'omnibarPrefixVideoPipTitle' },
    popup: { classes: ['popup-btn'], tooltip: 'openAsPopupTitle' },
    summary: { classes: ['gemini-summary-btn'], tooltip: 'summarizeWithGemini' },
    capture: { classes: ['screenshot-btn', 'view-screenshots-btn'], tooltip: 'captureFullPage' },
    qrcode: { classes: ['qr-code-btn'], tooltip: 'showQrCode' },
    cookies: { classes: ['edit-cookies-btn'], tooltip: 'editCookies' },
    download: { classes: ['download-files-btn'], tooltip: 'showDownloads' },
    bookmark: { classes: ['bookmark-btn'], tooltip: 'addToBookmarks' },
    overflow: { classes: ['overflow-btn'], tooltip: 'showOverflow' },
};

export const BOOKMARK_ACTION_GROUPS = {
    'b-add-folder': { classes: ['add-folder-btn'], tooltip: 'addNewFolder' },
    'b-open-all-bookmarks': { classes: ['open-all-btn'], tooltip: 'openAllBookmarks' },
    'b-rules': { classes: ['create-rule-btn'], tooltip: 'createRuleFromSubgroup' },
    'b-add-to-rule': { classes: ['add-to-rule-btn'], tooltip: 'addSubgroupToExistingRule' },
    'b-export': { classes: ['export-folder-btn'], tooltip: 'exportBookmarks' },
    'b-edit': { classes: ['edit-btn', 'edit-folder-btn'], tooltip: 'editBookmark' },
    'b-copy': { classes: ['copy-btn', 'copy-all-btn'], tooltip: 'copyUrl' },
    'b-delete': { classes: ['delete-btn'], tooltip: 'deleteBookmark' },
    'b-delete-folder': { classes: ['delete-folder-btn'], tooltip: 'deleteFolder' },
    'b-overflow': { classes: ['overflow-btn'], tooltip: 'showOverflow' },
};

export const noteConfig = {
    name: 'Notes',
    dbClearFunction: clearNotesForContext,
    persistentKey: STORAGE_KEYS.PERSISTENT_NOTES,
    sessionKey: STORAGE_KEYS.NOTES,
    notificationSuccess: 'allNotesDeleted',
    notificationError: 'errorDeletingNotes',
    notificationOrphanSuccess: 'allOrphanNotesDeleted',
    notificationNoOrphans: 'noOrphanNotesToDelete',
    getPersistentItemsFunction: async () => {
        const { [STORAGE_KEYS.PERSISTENT_NOTES]: ids = [] } = await chrome.storage.local.get(
            STORAGE_KEYS.PERSISTENT_NOTES,
        );
        if (ids.length === 0) return [];
        const items = await Promise.all(ids.map((id) => getNoteFromDb(id)));
        return items.filter(Boolean);
    },
    deleteItemFromDbFunction: deleteNoteFromDb,
};

export const screenshotConfig = {
    name: 'Screenshots',
    dbClearFunction: clearScreenshotsForContext,
    persistentKey: STORAGE_KEYS.PERSISTENT_SCREENSHOTS,
    sessionKey: STORAGE_KEYS.SCREENSHOTS,
    notificationSuccess: 'allScreenshotsDeleted',
    notificationError: 'errorDeletingScreenshots',
    notificationOrphanSuccess: 'allOrphanScreenshotsDeleted',
    notificationNoOrphans: 'noOrphanScreenshotsToDelete',
    getPersistentItemsFunction: async () => {
        const { [STORAGE_KEYS.PERSISTENT_SCREENSHOTS]: ids = [] } = await chrome.storage.local.get(
            STORAGE_KEYS.PERSISTENT_SCREENSHOTS,
        );
        if (ids.length === 0) return [];
        const items = await Promise.all(ids.map((id) => getScreenshotFromDb(id)));
        return items.filter(Boolean);
    },
    deleteItemFromDbFunction: deleteScreenshotFromDb,
};

export const state = {
    themeColors: {},
    currentColorPopup: null,
    currentDownloadModal: null,
    lastClickedIndicator: null,
    isPerformingProgrammaticUpdate: false,
    userDefinedOrder: [],
    pinnedGroupIds: new Set(),
    hiddenGroupIds: new Set(),
    pinnedAtLastPositionId: null,
    isUrlViewActive: false,
    isGeminiViewActive: false,
    isStandaloneGemini: false,
    isGalleryViewActive: false,
    currentGalleryContext: null,
    isNotesViewActive: false,
    currentNotesContext: null,
    expandedGroupStates: new Map(),
    expandedSubgroupStates: new Map(),
    isInitialRender: true,
    hiddenYoutubeView: null,
    splitScreenState: {},
    currentPanelUrl: null,
    currentPanelContext: null,
    previousIframeUrl: null,
    settings: {},
    elementToFocusAfterRender: null,
    searchState: { results: [], currentIndex: -1 },
    lastSearchTerm: '',
    conversationHistory: [],
    currentSpeechUtterance: null,
    currentlySpeakingEntryId: null,
    speechKeepAliveInterval: null,
    isSpeechPaused: false,
    pendingDeletionGroupIds: new Set(),
    activeNoteFilters: { cat: null, context: null, type: null, pomo: null },
    lastIframeSearchResultCount: 0,
    persistentNoteIds: new Set(),
    availableGeminiModels: [],
    selectedGeminiModel: 'gemini-2.5-flash',
    agentModeEnabled: false,
    agentConversationContents: [],
    pendingAttachments: [],
    persistentConversations: [],
    combinedConversations: [],
    currentCombinedIndex: -1,
    sessionConversations: [],
    currentSessionConversationIndex: -1,
    geminiModelDropdown: null,
    isGlobalPlaybackActive: false,
    globalPlaybackChunks: [],
    currentGlobalChunkIndex: 0,
    isBookmarksViewActive: false,
    isPopupWindow: false,
    activeContextMenu: null,
    backedUpGroupData: {},
    restoredGroupIds: new Set(),
    currentlyEditingInput: null,
    currentBookmarkSort: 'dateAdded',
    isAllExpanded: true,
    isRenderingBookmarks: false,
    isHandlingBookmarkChange: false,
    currentHistoryDateFilter: null,
    bookmarkActionVisibilitySettings: {},
    calCurrentDate: new Date(),
    calSelectedDate: null,
    navigationHistory: [],
    currentMainView: 'groups',
    viewExpandStates: {
        groups: true,
        bookmarks: true,
        gemini: true,
        notes: true,
    },
    visibilitySettings: {
        showGroupActions: false,
        showSubgroupActions: false,
        showTabActions: false,
        showDomainHeaders: false,
        showFolderActions: false,
        showChildFolders: true,
        showChildFolderActions: false,
        showBookmarkActions: false,
    },
    actionVisibilitySettings: {},
    isProgrammaticActivation: false,
    geminiScheduleEditorState: {
        mode: 'add',
        scheduleIndex: -1,
    },
    prefetchCache: {
        bookmarks: null,
        history: null,
        recent: null,
        reading: null,
    },
    historyRenderLimit: 150,
    isRenderingHistory: false,
    lastHistoryParams: { startTime: null, endTime: null, searchTerm: '' },
};
